---
- name: Installing FreeIPA clients and registering them with the server
  hosts: all

  vars:
    ipa_server: utility.lab.example.com
    ipa_domain: lab.example.com
    ipa_realm: LAB.EXAMPLE.COM
    ipa_admin_password: redhat321
    ipa_client_packages:
      - freeipa-client
      - ipa-admintools

  tasks:
    - name: Set up host account on FreeIPA server
      ipa_host:
        fqdn: "{{ ansible_fqdn }}"
        state: present
        force: yes
        ipa_host: "{{ ipa_server }}"
        ipa_user: admin
        ipa_pass: "{{ ipa_admin_password }}"
        validate_certs: no
      delegate_to: "{{ ipa_server }}"
      ignore_errors: yes

    - name: FreeIPA client packages installed
      yum:
        name: "{{ ipa_client_packages }}"
        state: present

    - name: Checking if the client can query the FreeIPA server
      shell:
        cmd: "echo redhat321 | kinit -f admin ; ipa host-find"
      failed_when: no
      changed_when: no
      register: ipa

    - name: Ensuring FreeIPA on the host is not installed
      command:
        cmd: ipa-client-install --uninstall --unattended
      failed_when: no
      when: ipa['rc'] != 0

    - name: Register system to host account on FreeIPA server
      command: >
        ipa-client-install
        --server={{ ipa_server }}
        --domain={{ ipa_domain }}
        --realm={{ ipa_realm }}
        --principal=admin
        --password={{ ipa_admin_password }}
        --no-ntp
        --mkhomedir
        --unattended
        --force
        --force-join
      register: result
      failed_when: result.rc != 0 and result.rc != 3
      when: ipa['rc'] != 0

    - name: Adding hosts to host groups
      delegate_to: "{{ ipa_server }}"
      run_once: yes
      block:

        - name: Host is registered to development hostgroup
          ipa_hostgroup:
            cn: development
            state: present
            host:
              - servera.lab.example.com
              - serverb.lab.example.com
            ipa_host: "{{ ipa_server }}"
            ipa_user: admin
            ipa_pass: "{{ ipa_admin_password }}"
            validate_certs: no

        - name: Host is registered to testing hostgroup
          ipa_hostgroup:
            cn: testing
            state: present
            host:
              - serverc.lab.example.com
              - serverd.lab.example.com
            ipa_host: "{{ ipa_server }}"
            ipa_user: admin
            ipa_pass: "{{ ipa_admin_password }}"
            validate_certs: no

        - name: Host is registered to production hostgroup
          ipa_hostgroup:
            cn: production
            state: present
            host:
              - servere.lab.example.com
              - serverf.lab.example.com
            ipa_host: "{{ ipa_server }}"
            ipa_user: admin
            ipa_pass: "{{ ipa_admin_password }}"
            validate_certs: no

    - name: Get TLS/SSL certificate from FreeIPA CA
      command: >
        ipa-getcert request -r
        -f /etc/pki/tls/certs/{{ ansible_fqdn }}.crt
        -k /etc/pki/tls/private/{{ ansible_fqdn }}.key
      ignore_errors: yes
...
